#:schema node_modules/wrangler/config-schema.json
name = "senecas-letters"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

# Custom domains
[[routes]]
pattern = "seneca.ink"
custom_domain = true

[[routes]]
pattern = "www.seneca.ink"
custom_domain = true