#:schema node_modules/wrangler/config-schema.json
name = "senecas-letters"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[env.production]
name = "senecas-letters"
workers_dev = true

[env.staging]
name = "senecas-letters-staging"
workers_dev = true