#:schema node_modules/wrangler/config-schema.json
name = "senecas-letters"
main = "dist/_worker.js"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "senecas-letters"

[env.staging]
name = "senecas-letters-staging"